export enum ProtectedAreaTypeEnum {
  RESERVA_LEGAL_APP = 1,
  AREA_URBANA = 2,
  MANANCIAL_PARA_ABASTECIMENTO = 3,
  MANANCIAL = 4,
  MORADIA_ISOLADA = 5,
  AGRUPAMENTO_DE_ANIMAIS = 6,
  SERICICULTURA = 7,
}
