services:
  db:
    container_name: 'aeroguard-db'
    image: postgis/postgis:13-3.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aeroguard
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/create-schemas.sql:/docker-entrypoint-initdb.d/create-schemas.sql

  app:
    container_name: 'aeroguard-app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@aeroguard-db:5432/aeroguard'
      NODE_ENV: development

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://aeroguard-db:5432/aeroguard?currentSchema=sonar
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: postgres
    ports:
      - "9000:9000"
    depends_on:
      - db
volumes:
  db_data:
