-- CreateTable
CREATE TABLE "SIGA"."S_AREA_ORGANIZACAO" (
    "ID_AREA_ORGANIZACAO" SERIAL NOT NULL,
    "PG_GEOMETRIA" public.geometry(polygonz, 4326) NOT NULL,
    "PG_GEOMETRIA_JSON" TEXT NOT NULL,
    "ID_ORGANIZACAO" INTEGER NOT NULL,
    "NM_CRIADO_POR" VARCHAR(30) NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_AREA_ORGANIZACAO" PRIMARY KEY ("ID_AREA_ORGANIZACAO")
);

-- CreateIndex
CREATE INDEX "I_AREA_ORGANIZACAO_PG_GEOM" ON "SIGA"."S_AREA_ORGANIZACAO" USING GIST ("PG_GEOMETRIA");

-- AddForeignKey
ALTER TABLE "SIGA"."S_AREA_ORGANIZACAO" ADD CONSTRAINT "S_AREA_ORGANIZACAO_ID_ORGANIZACAO_fkey" FOREIGN KEY ("ID_ORGANIZACAO") REFERENCES "SIGA"."S_ORGANIZACAO"("ID_ORGANIZACAO") ON DELETE RESTRICT ON UPDATE CASCADE;
