-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "SIGA";

-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "postgis";

-- CreateEnum
CREATE TYPE "SIGA"."STATUS_USUARIO" AS ENUM ('ATIVO', 'INATIVO', 'CONVIDADO');

-- CreateEnum
CREATE TYPE "SIGA"."STATUS_ANALISE_APLICACAO" AS ENUM ('PENDING', 'APPROVED', 'FAILED', 'REJECTED');

-- CreateEnum
CREATE TYPE "SIGA"."NIVEL_ALERTA_NOTIFICACAO" AS ENUM ('GRAVISSIMO', 'GRAVE', 'MODERADO', 'LEVE');

-- CreateTable
CREATE TABLE "SIGA"."S_USUARIO" (
    "ID_USUARIO" SERIAL NOT NULL,
    "NM_USUARIO" VARCHAR(100) NOT NULL,
    "DS_EMAIL" VARCHAR(100) NOT NULL,
    "DS_DOCUMENTO" VARCHAR(14) NOT NULL,
    "CS_STATUS" "SIGA"."STATUS_USUARIO" NOT NULL DEFAULT 'ATIVO',
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_USUARIO" PRIMARY KEY ("ID_USUARIO")
);

-- CreateTable
CREATE TABLE "SIGA"."S_ORGANIZACAO" (
    "ID_ORGANIZACAO" SERIAL NOT NULL,
    "NM_ORGANIZACAO" VARCHAR(100) NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_ORGANIZACAO" PRIMARY KEY ("ID_ORGANIZACAO")
);

-- CreateTable
CREATE TABLE "SIGA"."S_USUARIO_ORGANIZACAO" (
    "ID_USUARIO" INTEGER NOT NULL,
    "ID_ORGANIZACAO" INTEGER NOT NULL,
    "ST_ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "NM_ATUALIZADO_POR" VARCHAR(30) NOT NULL,
    "NM_CRIADO_POR" VARCHAR(30) NOT NULL,
    "DH_ATUALIZACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_USUARIO_ORGANIZACAO" PRIMARY KEY ("ID_USUARIO","ID_ORGANIZACAO")
);

-- CreateTable
CREATE TABLE "SIGA"."S_PILOTO" (
    "ID_PILOTO" SERIAL NOT NULL,
    "ID_ORGANIZACAO" INTEGER NOT NULL,
    "NM_PILOTO" VARCHAR(100) NOT NULL,
    "CD_DOCUMENTO" CHAR(14) NOT NULL,
    "CD_LICENCA" CHAR(20) NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_PILOTO" PRIMARY KEY ("ID_PILOTO")
);

-- CreateTable
CREATE TABLE "SIGA"."S_APLICACAO" (
    "ID_APLICACAO" BIGSERIAL NOT NULL,
    "ID_USUARIO" INTEGER NOT NULL,
    "ID_ORGANIZACAO" INTEGER NOT NULL,
    "NM_VEICULO" VARCHAR(100) NOT NULL,
    "DH_INICIO" TIMESTAMP(3) NOT NULL,
    "DH_FIM" TIMESTAMP(3) NOT NULL,
    "NM_CRIADO_POR" VARCHAR(30) NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_APLICACAO" PRIMARY KEY ("ID_APLICACAO")
);

-- CreateTable
CREATE TABLE "SIGA"."H_EVENTO_APLICACAO" (
    "ID_EVENTO_APLICACAO" BIGSERIAL NOT NULL,
    "ID_APLICACAO" BIGINT NOT NULL,
    "ID_STATUS_APLICACAO" INTEGER NOT NULL,
    "ID_PILOTO" INTEGER NOT NULL,
    "NM_CRIADO_POR" VARCHAR(30) NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_H_EVENTO_APLICACAO" PRIMARY KEY ("ID_EVENTO_APLICACAO")
);

-- CreateTable
CREATE TABLE "SIGA"."S_STATUS_APLICACAO" (
    "ID_STATUS_APLICACAO" SERIAL NOT NULL,
    "DS_DESCRICAO" VARCHAR(100) NOT NULL,
    "ST_ATIVO" BOOLEAN NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_STATUS_APLICACAO" PRIMARY KEY ("ID_STATUS_APLICACAO")
);

-- CreateTable
CREATE TABLE "SIGA"."S_DOCUMENTO_APLICACAO" (
    "ID_DOCUMENTO_APLICACAO" SERIAL NOT NULL,
    "ID_APLICACAO" BIGINT NOT NULL,
    "ID_TIPO_DOCUMENTO_APLICACAO" INTEGER NOT NULL,
    "NM_NOME_ORIGINAL" VARCHAR(200) NOT NULL,
    "DS_CAMINHO" VARCHAR(1000) NOT NULL,

    CONSTRAINT "PK_DOCUMENTO_APLICACAO" PRIMARY KEY ("ID_DOCUMENTO_APLICACAO")
);

-- CreateTable
CREATE TABLE "SIGA"."S_DOCUMENTO_DADOS_APLICACAO" (
    "ID_DOCUMENTO_DADOS" BIGSERIAL NOT NULL,
    "ID_DOCUMENTO_APLICACAO" INTEGER NOT NULL,
    "DS_CHAVE" VARCHAR(100) NOT NULL,
    "DS_VALOR" VARCHAR(200),
    "ID_CRIADO_POR" INTEGER NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_DOCUMENTO_DADOS_APLICACAO" PRIMARY KEY ("ID_DOCUMENTO_DADOS")
);

-- CreateTable
CREATE TABLE "SIGA"."S_TIPO_DOCUMENTO_APLICACAO" (
    "ID_TIPO_DOCUMENTO_APLICACAO" SERIAL NOT NULL,
    "DS_DESCRICAO" VARCHAR(100) NOT NULL,
    "ST_ATIVO" BOOLEAN NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_TIPO_DOCUMENTO_APLICACAO" PRIMARY KEY ("ID_TIPO_DOCUMENTO_APLICACAO")
);

-- CreateTable
CREATE TABLE "SIGA"."S_AREA_APLICACAO" (
    "ID_AREA_APLICACAO" SERIAL NOT NULL,
    "PG_GEOMETRIA" public.geometry(polygonz, 4326) NOT NULL,
    "PG_GEOMETRIA_JSON" TEXT NOT NULL,
    "DS_DESCRICAO" VARCHAR(100) NOT NULL,
    "ID_APLICACAO" BIGINT NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_AREA_APLICACAO" PRIMARY KEY ("ID_AREA_APLICACAO")
);

-- CreateTable
CREATE TABLE "SIGA"."S_ANALISE_APLICACAO" (
    "ID_ANALISE_APLICACAO" SERIAL NOT NULL,
    "ID_TIPO_ANALISE_APLICACAO" INTEGER NOT NULL,
    "ID_APLICACAO" BIGINT NOT NULL,
    "ID_NOTIFICACAO_APLICACAO" BIGINT,
    "NR_TEMPO_DECORRIDO" INTEGER NOT NULL,
    "CS_STATUS" "SIGA"."STATUS_ANALISE_APLICACAO" NOT NULL DEFAULT 'PENDING',
    "DETALHES" JSONB,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_ANALISE_APLICACAO" PRIMARY KEY ("ID_ANALISE_APLICACAO")
);

-- CreateTable
CREATE TABLE "SIGA"."S_TIPO_ANALISE_APLICACAO" (
    "ID_TIPO_ANALISE_APLICACAO" SERIAL NOT NULL,
    "DS_NOME" VARCHAR(100) NOT NULL,
    "ST_PERMITIR_REPROCESSAMENTO" BOOLEAN NOT NULL DEFAULT true,
    "ST_ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_TIPO_ANALISE_APLICACAO" PRIMARY KEY ("ID_TIPO_ANALISE_APLICACAO")
);

-- CreateTable
CREATE TABLE "SIGA"."S_NOTIFICACAO_APLICACAO" (
    "ID_NOTIFICACAO_APLICACAO" BIGSERIAL NOT NULL,
    "ID_APLICACAO" BIGINT NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_FISCAL" INTEGER NOT NULL,
    "CS_NIVEL_ALERTA" "SIGA"."NIVEL_ALERTA_NOTIFICACAO" NOT NULL DEFAULT 'LEVE',

    CONSTRAINT "PK_NOTIFICACAO_APLICACAO" PRIMARY KEY ("ID_NOTIFICACAO_APLICACAO")
);

-- CreateTable
CREATE TABLE "SIGA"."H_EVENTO_NOTIFICACAO" (
    "ID_EVENTO_NOTIFICACAO" BIGSERIAL NOT NULL,
    "ID_NOTIFICACAO_APLICACAO" BIGINT NOT NULL,
    "ID_STATUS_NOTIFICACAO_APLICACAO" INTEGER NOT NULL,
    "NM_CRIADO_POR" VARCHAR(30) NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_EVENTO_NOTIFICACAO" PRIMARY KEY ("ID_EVENTO_NOTIFICACAO")
);

-- CreateTable
CREATE TABLE "SIGA"."S_STATUS_NOTIFICACAO" (
    "ID_STATUS_NOTIFICACAO" SERIAL NOT NULL,
    "DS_DESCRICAO" VARCHAR(100) NOT NULL,
    "ST_ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_STATUS_NOTIFICACAO" PRIMARY KEY ("ID_STATUS_NOTIFICACAO")
);

-- CreateTable
CREATE TABLE "SIGA"."S_AREA_PROTEGIDA" (
    "ID_AREA_PROTEGIDA" SERIAL NOT NULL,
    "PG_GEOMETRIA" public.geometry(polygonz, 4326) NOT NULL,
    "PG_GEOMETRIA_JSON" TEXT NOT NULL,
    "DS_DESCRICAO" VARCHAR(100) NOT NULL,
    "ID_TIPO_AREA_PROTEGIDA" INTEGER NOT NULL,
    "ID_ORGANIZACAO" INTEGER NOT NULL,
    "NM_CRIADO_POR" VARCHAR(30) NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_AREA_PROTEGIDA" PRIMARY KEY ("ID_AREA_PROTEGIDA")
);

-- CreateTable
CREATE TABLE "SIGA"."S_TIPO_AREA_PROTEGIDA" (
    "ID_TIPO_AREA_PROTEGIDA" SERIAL NOT NULL,
    "NM_TIPO_AREA_PROTEGIDA" VARCHAR(50) NOT NULL,
    "DS_DESCRICAO" VARCHAR(200) NOT NULL,
    "NR_DISTANCIA" INTEGER NOT NULL,
    "NR_DISTANCIA_DRONE" INTEGER NOT NULL,
    "ST_ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_TIPO_AREA_PROTEGIDA" PRIMARY KEY ("ID_TIPO_AREA_PROTEGIDA")
);

-- CreateTable
CREATE TABLE "SIGA"."S_CAMINHO_APLICACAO" (
    "ID_CAMINHO_APLICACAO" SERIAL NOT NULL,
    "PG_GEOMETRIA" public.geometry(linestringz, 4326) NOT NULL,
    "PG_GEOMETRIA_JSON" TEXT NOT NULL,
    "DS_DESCRICAO" VARCHAR(100) NOT NULL,
    "ID_APLICACAO" BIGINT NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PK_CAMINHO_APLICACAO" PRIMARY KEY ("ID_CAMINHO_APLICACAO")
);

-- CreateIndex
CREATE INDEX "I_APL_ID_USR_DH_CRIACAO" ON "SIGA"."S_APLICACAO"("ID_USUARIO", "DH_CRIACAO" DESC);

-- CreateIndex
CREATE INDEX "IAD_H_EVT_APL_ID_APL_DH_CRI" ON "SIGA"."H_EVENTO_APLICACAO"("ID_APLICACAO", "DH_CRIACAO" DESC);

-- CreateIndex
CREATE INDEX "I_APL_AREA_PG_GEOM" ON "SIGA"."S_AREA_APLICACAO" USING GIST ("PG_GEOMETRIA");

-- CreateIndex
CREATE INDEX "I_AREA_PROTEGIDA_PG_GEOM" ON "SIGA"."S_AREA_PROTEGIDA" USING GIST ("PG_GEOMETRIA");

-- CreateIndex
CREATE INDEX "I_CAMINHO_APL_PG_GEOM" ON "SIGA"."S_CAMINHO_APLICACAO" USING GIST ("PG_GEOMETRIA");

-- AddForeignKey
ALTER TABLE "SIGA"."S_USUARIO_ORGANIZACAO" ADD CONSTRAINT "FK_USR_ORG_ID_ORG" FOREIGN KEY ("ID_ORGANIZACAO") REFERENCES "SIGA"."S_ORGANIZACAO"("ID_ORGANIZACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."S_USUARIO_ORGANIZACAO" ADD CONSTRAINT "S_USR_ORG_ID_USR" FOREIGN KEY ("ID_USUARIO") REFERENCES "SIGA"."S_USUARIO"("ID_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."S_PILOTO" ADD CONSTRAINT "FK_PILOTO_ID_ORG" FOREIGN KEY ("ID_ORGANIZACAO") REFERENCES "SIGA"."S_ORGANIZACAO"("ID_ORGANIZACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."S_APLICACAO" ADD CONSTRAINT "FK_APL_ID_USR" FOREIGN KEY ("ID_USUARIO") REFERENCES "SIGA"."S_USUARIO"("ID_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."S_APLICACAO" ADD CONSTRAINT "FK_APL_ID_ORG" FOREIGN KEY ("ID_ORGANIZACAO") REFERENCES "SIGA"."S_ORGANIZACAO"("ID_ORGANIZACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."H_EVENTO_APLICACAO" ADD CONSTRAINT "FK_H_EVT_APL_ID_APLI" FOREIGN KEY ("ID_APLICACAO") REFERENCES "SIGA"."S_APLICACAO"("ID_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."H_EVENTO_APLICACAO" ADD CONSTRAINT "FK_H_EVT_APL_ID_STATUS_APL" FOREIGN KEY ("ID_STATUS_APLICACAO") REFERENCES "SIGA"."S_STATUS_APLICACAO"("ID_STATUS_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."H_EVENTO_APLICACAO" ADD CONSTRAINT "FK_H_EVT_APL_ID_PILOTO" FOREIGN KEY ("ID_PILOTO") REFERENCES "SIGA"."S_PILOTO"("ID_PILOTO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."S_DOCUMENTO_APLICACAO" ADD CONSTRAINT "FK_DOC_APL_ID_APL" FOREIGN KEY ("ID_APLICACAO") REFERENCES "SIGA"."S_APLICACAO"("ID_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."S_DOCUMENTO_APLICACAO" ADD CONSTRAINT "FK_DOC_APL_ID_TP_DOC_APL" FOREIGN KEY ("ID_TIPO_DOCUMENTO_APLICACAO") REFERENCES "SIGA"."S_TIPO_DOCUMENTO_APLICACAO"("ID_TIPO_DOCUMENTO_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."S_DOCUMENTO_DADOS_APLICACAO" ADD CONSTRAINT "FK_DOC_DADOS_APL_ID_DOC_APL" FOREIGN KEY ("ID_DOCUMENTO_APLICACAO") REFERENCES "SIGA"."S_DOCUMENTO_APLICACAO"("ID_DOCUMENTO_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."S_AREA_APLICACAO" ADD CONSTRAINT "FK_AREA_APL_ID_APL" FOREIGN KEY ("ID_APLICACAO") REFERENCES "SIGA"."S_APLICACAO"("ID_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."S_ANALISE_APLICACAO" ADD CONSTRAINT "FK_ANL_APL_ID_APL" FOREIGN KEY ("ID_APLICACAO") REFERENCES "SIGA"."S_APLICACAO"("ID_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."S_ANALISE_APLICACAO" ADD CONSTRAINT "FK_ANL_APL_ID_TP_ANL_APL" FOREIGN KEY ("ID_TIPO_ANALISE_APLICACAO") REFERENCES "SIGA"."S_TIPO_ANALISE_APLICACAO"("ID_TIPO_ANALISE_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."S_ANALISE_APLICACAO" ADD CONSTRAINT "FK_ANL_APL_ID_NOT_APL" FOREIGN KEY ("ID_NOTIFICACAO_APLICACAO") REFERENCES "SIGA"."S_NOTIFICACAO_APLICACAO"("ID_NOTIFICACAO_APLICACAO") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."S_NOTIFICACAO_APLICACAO" ADD CONSTRAINT "FK_NOT_APL_ID_APL" FOREIGN KEY ("ID_APLICACAO") REFERENCES "SIGA"."S_APLICACAO"("ID_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."S_NOTIFICACAO_APLICACAO" ADD CONSTRAINT "FK_NOT_APL_ID_FISCAL" FOREIGN KEY ("ID_FISCAL") REFERENCES "SIGA"."S_USUARIO"("ID_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."H_EVENTO_NOTIFICACAO" ADD CONSTRAINT "FK_H_EVT_NOT_ID_STATUS_NOT_APL" FOREIGN KEY ("ID_STATUS_NOTIFICACAO_APLICACAO") REFERENCES "SIGA"."S_STATUS_NOTIFICACAO"("ID_STATUS_NOTIFICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."H_EVENTO_NOTIFICACAO" ADD CONSTRAINT "FK_H_EVT_NOT_ID_NOT_APL" FOREIGN KEY ("ID_NOTIFICACAO_APLICACAO") REFERENCES "SIGA"."S_NOTIFICACAO_APLICACAO"("ID_NOTIFICACAO_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."S_AREA_PROTEGIDA" ADD CONSTRAINT "FK_AREA_PROT_ID_TP_AREA_PROT" FOREIGN KEY ("ID_TIPO_AREA_PROTEGIDA") REFERENCES "SIGA"."S_TIPO_AREA_PROTEGIDA"("ID_TIPO_AREA_PROTEGIDA") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."S_AREA_PROTEGIDA" ADD CONSTRAINT "FK_AREA_PROT_ID_ORG" FOREIGN KEY ("ID_ORGANIZACAO") REFERENCES "SIGA"."S_ORGANIZACAO"("ID_ORGANIZACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."S_CAMINHO_APLICACAO" ADD CONSTRAINT "FK_CAMINHO_APL_ID_APL" FOREIGN KEY ("ID_APLICACAO") REFERENCES "SIGA"."S_APLICACAO"("ID_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;
