POST {{host}}/v1/applications
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "vehicle": "brave",
  "startDate": "2025-08-16T16:11:01Z",
  "endDate": "2025-08-16T17:30:00Z",
  "pilot": {
    "id": 1
  }
}

###

GET {{host}}/v1/applications
  ?page=1
  &pageSize=10
Authorization: Bearer {{token}}

####

GET {{host}}/v1/applications/1
Authorization: Bearer {{token}}

####

PATCH  {{host}}/v1/applications/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "vehicle": "brave",
  "startDate": "2024-06-25T20:11:01Z",
  "endDate": "2024-06-25T23:30:00Z",
  "pilot": {
    "id": 1
  },
  "status": {
    "id": 2
  }
}

###

POST {{host}}/v1/applications/2/finish
Content-Type: application/json
Authorization: Bearer {{token}}
