-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "postgis";

-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'INVITED');

-- CreateEnum
CREATE TYPE "ApplicationAnalisysStatus" AS ENUM ('PENDING', 'APPROVED', 'FAILED', 'REJECTED');

-- CreateEnum
CREATE TYPE "NotificationAlertLevel" AS ENUM ('GRAVISSIMO', 'GRAVE', 'MODERADO', 'LEVE');

-- CreateTable
CREATE TABLE "S_USUARIO" (
    "ID_USUARIO" SERIAL NOT NULL,
    "NM_USUARIO" VARCHAR(100) NOT NULL,
    "DS_EMAIL" VARCHAR(100) NOT NULL,
    "DS_DOCUMENTO" VARCHAR(14) NOT NULL,
    "CS_STATUS" "UserStatus" NOT NULL DEFAULT 'ACTIVE',
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "S_USUARIO_pkey" PRIMARY KEY ("ID_USUARIO")
);

-- CreateTable
CREATE TABLE "S_ORGANIZACAO" (
    "ID_ORGANIZACAO" SERIAL NOT NULL,
    "NM_ORGANIZACAO" VARCHAR(100) NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "S_ORGANIZACAO_pkey" PRIMARY KEY ("ID_ORGANIZACAO")
);

-- CreateTable
CREATE TABLE "S_USUARIO_ORGANIZACAO" (
    "ID_USUARIO" INTEGER NOT NULL,
    "ID_ORGANIZACAO" INTEGER NOT NULL,
    "ST_ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "NM_ATUALIZADO_POR" VARCHAR(30) NOT NULL,
    "NM_CRIADO_POR" VARCHAR(30) NOT NULL,
    "DH_ATUALIZACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "S_USUARIO_ORGANIZACAO_pkey" PRIMARY KEY ("ID_USUARIO","ID_ORGANIZACAO")
);

-- CreateTable
CREATE TABLE "S_PILOTO" (
    "ID_PILOTO" SERIAL NOT NULL,
    "ID_ORGANIZACAO" INTEGER NOT NULL,
    "NM_PILOTO" VARCHAR(100) NOT NULL,
    "NR_DOCUMENTO" VARCHAR(14) NOT NULL,
    "NR_LICENCA" VARCHAR(20) NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "S_PILOTO_pkey" PRIMARY KEY ("ID_PILOTO")
);

-- CreateTable
CREATE TABLE "S_APLICACAO" (
    "ID_APLICACAO" BIGSERIAL NOT NULL,
    "ID_USUARIO" INTEGER NOT NULL,
    "ID_ORGANIZACAO" INTEGER NOT NULL,
    "NM_VEICULO" VARCHAR(100) NOT NULL,
    "DH_INICIO" TIMESTAMP(3) NOT NULL,
    "DH_FIM" TIMESTAMP(3) NOT NULL,
    "NM_CRIADO_POR" VARCHAR(30) NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "S_APLICACAO_pkey" PRIMARY KEY ("ID_APLICACAO")
);

-- CreateTable
CREATE TABLE "H_EVENTO_APLICACAO" (
    "ID_EVENTO_APLICACAO" BIGSERIAL NOT NULL,
    "ID_APLICACAO" BIGINT NOT NULL,
    "ID_STATUS_APLICACAO" INTEGER NOT NULL,
    "ID_PILOTO" INTEGER NOT NULL,
    "NM_CRIADO_POR" VARCHAR(30) NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "H_EVENTO_APLICACAO_pkey" PRIMARY KEY ("ID_EVENTO_APLICACAO")
);

-- CreateTable
CREATE TABLE "S_STATUS_APLICACAO" (
    "ID_STATUS_APLICACAO" SERIAL NOT NULL,
    "DS_DESCRICAO" VARCHAR(100) NOT NULL,
    "ST_ATIVO" BOOLEAN NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "S_STATUS_APLICACAO_pkey" PRIMARY KEY ("ID_STATUS_APLICACAO")
);

-- CreateTable
CREATE TABLE "S_DOCUMENTO_APLICACAO" (
    "ID_DOCUMENTO_APLICACAO" SERIAL NOT NULL,
    "ID_APLICACAO" BIGINT NOT NULL,
    "ID_TIPO_DOCUMENTO_APLICACAO" INTEGER NOT NULL,
    "NM_NOME_ORIGINAL" VARCHAR(200) NOT NULL,
    "DS_CAMINHO" VARCHAR(1000) NOT NULL,

    CONSTRAINT "S_DOCUMENTO_APLICACAO_pkey" PRIMARY KEY ("ID_DOCUMENTO_APLICACAO")
);

-- CreateTable
CREATE TABLE "S_DOCUMENTO_DADOS_APLICACAO" (
    "ID_DOCUMENTO_DADOS" BIGSERIAL NOT NULL,
    "ID_DOCUMENTO_APLICACAO" INTEGER NOT NULL,
    "DS_CHAVE" VARCHAR(100) NOT NULL,
    "DS_VALOR" VARCHAR(200),
    "ID_CRIADO_POR" INTEGER NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "S_DOCUMENTO_DADOS_APLICACAO_pkey" PRIMARY KEY ("ID_DOCUMENTO_DADOS")
);

-- CreateTable
CREATE TABLE "S_TIPO_DOCUMENTO_APLICACAO" (
    "ID_TIPO_DOCUMENTO_APLICACAO" SERIAL NOT NULL,
    "DS_DESCRICAO" VARCHAR(100) NOT NULL,
    "ST_ATIVO" BOOLEAN NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "S_TIPO_DOCUMENTO_APLICACAO_pkey" PRIMARY KEY ("ID_TIPO_DOCUMENTO_APLICACAO")
);

-- CreateTable
CREATE TABLE "S_AREA_APLICACAO" (
    "ID_AREA_APLICACAO" SERIAL NOT NULL,
    "GEOMETRIA" public.geometry(polygonz, 4326) NOT NULL,
    "GEOMETRIA_JSON" TEXT NOT NULL,
    "DS_DESCRICAO" VARCHAR(100) NOT NULL,
    "ID_APLICACAO" BIGINT NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "S_AREA_APLICACAO_pkey" PRIMARY KEY ("ID_AREA_APLICACAO")
);

-- CreateTable
CREATE TABLE "S_ANALISE_APLICACAO" (
    "ID_ANALISE_APLICACAO" SERIAL NOT NULL,
    "ID_TIPO_ANALISE_APLICACAO" INTEGER NOT NULL,
    "ID_APLICACAO" BIGINT NOT NULL,
    "ID_NOTIFICACAO_APLICACAO" BIGINT,
    "NR_TEMPO_DECORRIDO" INTEGER NOT NULL,
    "CS_STATUS" "ApplicationAnalisysStatus" NOT NULL DEFAULT 'PENDING',
    "DETALHES" JSONB,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "S_ANALISE_APLICACAO_pkey" PRIMARY KEY ("ID_ANALISE_APLICACAO")
);

-- CreateTable
CREATE TABLE "S_TIPO_ANALISE_APLICACAO" (
    "ID_TIPO_ANALISE_APLICACAO" SERIAL NOT NULL,
    "DS_NOME" VARCHAR(100) NOT NULL,
    "PERMITIR_REPROCESSAMENTO" BOOLEAN NOT NULL DEFAULT true,
    "ST_ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "S_TIPO_ANALISE_APLICACAO_pkey" PRIMARY KEY ("ID_TIPO_ANALISE_APLICACAO")
);

-- CreateTable
CREATE TABLE "S_NOTIFICACAO_APLICACAO" (
    "ID_NOTIFICACAO_APLICACAO" BIGSERIAL NOT NULL,
    "ID_APLICACAO" BIGINT NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_FISCAL" INTEGER NOT NULL,
    "CS_NIVEL_ALERTA" "NotificationAlertLevel" NOT NULL DEFAULT 'LEVE',

    CONSTRAINT "S_NOTIFICACAO_APLICACAO_pkey" PRIMARY KEY ("ID_NOTIFICACAO_APLICACAO")
);

-- CreateTable
CREATE TABLE "H_EVENTO_NOTIFICACAO" (
    "ID_EVENTO_NOTIFICACAO" BIGSERIAL NOT NULL,
    "ID_NOTIFICACAO_APLICACAO" BIGINT NOT NULL,
    "ID_STATUS_NOTIFICACAO_APLICACAO" INTEGER NOT NULL,
    "NM_CRIADO_POR" VARCHAR(30) NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "H_EVENTO_NOTIFICACAO_pkey" PRIMARY KEY ("ID_EVENTO_NOTIFICACAO")
);

-- CreateTable
CREATE TABLE "S_STATUS_NOTIFICACAO" (
    "ID_STATUS_NOTIFICACAO" SERIAL NOT NULL,
    "DS_DESCRICAO" VARCHAR(100) NOT NULL,
    "ST_ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "S_STATUS_NOTIFICACAO_pkey" PRIMARY KEY ("ID_STATUS_NOTIFICACAO")
);

-- CreateTable
CREATE TABLE "S_AREA_PROTEGIDA" (
    "ID_AREA_PROTEGIDA" SERIAL NOT NULL,
    "GEOMETRIA" public.geometry(polygonz, 4326) NOT NULL,
    "GEOMETRIA_JSON" TEXT NOT NULL,
    "DS_DESCRICAO" VARCHAR(100) NOT NULL,
    "ID_TIPO_AREA_PROTEGIDA" INTEGER NOT NULL,
    "ID_ORGANIZACAO" INTEGER NOT NULL,
    "NM_CRIADO_POR" VARCHAR(30) NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "S_AREA_PROTEGIDA_pkey" PRIMARY KEY ("ID_AREA_PROTEGIDA")
);

-- CreateTable
CREATE TABLE "S_TIPO_AREA_PROTEGIDA" (
    "ID_TIPO_AREA_PROTEGIDA" SERIAL NOT NULL,
    "NM_TIPO_AREA_PROTEGIDA" VARCHAR(50) NOT NULL,
    "DS_DESCRICAO" VARCHAR(200) NOT NULL,
    "NR_DISTANCIA" INTEGER NOT NULL,
    "NR_DISTANCIA_DRONE" INTEGER NOT NULL,
    "ST_ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "S_TIPO_AREA_PROTEGIDA_pkey" PRIMARY KEY ("ID_TIPO_AREA_PROTEGIDA")
);

-- CreateTable
CREATE TABLE "S_CAMINHO_APLICACAO" (
    "ID_CAMINHO_APLICACAO" SERIAL NOT NULL,
    "GEOMETRIA" public.geometry(linestringz, 4326) NOT NULL,
    "GEOMETRIA_JSON" TEXT NOT NULL,
    "DS_DESCRICAO" VARCHAR(100) NOT NULL,
    "ID_APLICACAO" BIGINT NOT NULL,
    "DH_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "S_CAMINHO_APLICACAO_pkey" PRIMARY KEY ("ID_CAMINHO_APLICACAO")
);

-- CreateIndex
CREATE INDEX "S_APLICACAO_ID_USUARIO_DH_CRIACAO_idx" ON "S_APLICACAO"("ID_USUARIO", "DH_CRIACAO" DESC);

-- CreateIndex
CREATE INDEX "H_EVENTO_APLICACAO_ID_APLICACAO_DH_CRIACAO_idx" ON "H_EVENTO_APLICACAO"("ID_APLICACAO", "DH_CRIACAO" DESC);

-- CreateIndex
CREATE INDEX "application_area_idx" ON "S_AREA_APLICACAO" USING GIST ("GEOMETRIA");

-- CreateIndex
CREATE INDEX "protected_area_idx" ON "S_AREA_PROTEGIDA" USING GIST ("GEOMETRIA");

-- CreateIndex
CREATE INDEX "application_path_idx" ON "S_CAMINHO_APLICACAO" USING GIST ("GEOMETRIA");

-- AddForeignKey
ALTER TABLE "S_USUARIO_ORGANIZACAO" ADD CONSTRAINT "S_USUARIO_ORGANIZACAO_ID_ORGANIZACAO_fkey" FOREIGN KEY ("ID_ORGANIZACAO") REFERENCES "S_ORGANIZACAO"("ID_ORGANIZACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "S_USUARIO_ORGANIZACAO" ADD CONSTRAINT "S_USUARIO_ORGANIZACAO_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "S_USUARIO"("ID_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "S_PILOTO" ADD CONSTRAINT "S_PILOTO_ID_ORGANIZACAO_fkey" FOREIGN KEY ("ID_ORGANIZACAO") REFERENCES "S_ORGANIZACAO"("ID_ORGANIZACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "S_APLICACAO" ADD CONSTRAINT "S_APLICACAO_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "S_USUARIO"("ID_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "S_APLICACAO" ADD CONSTRAINT "S_APLICACAO_ID_ORGANIZACAO_fkey" FOREIGN KEY ("ID_ORGANIZACAO") REFERENCES "S_ORGANIZACAO"("ID_ORGANIZACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "H_EVENTO_APLICACAO" ADD CONSTRAINT "H_EVENTO_APLICACAO_ID_APLICACAO_fkey" FOREIGN KEY ("ID_APLICACAO") REFERENCES "S_APLICACAO"("ID_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "H_EVENTO_APLICACAO" ADD CONSTRAINT "H_EVENTO_APLICACAO_ID_STATUS_APLICACAO_fkey" FOREIGN KEY ("ID_STATUS_APLICACAO") REFERENCES "S_STATUS_APLICACAO"("ID_STATUS_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "H_EVENTO_APLICACAO" ADD CONSTRAINT "H_EVENTO_APLICACAO_ID_PILOTO_fkey" FOREIGN KEY ("ID_PILOTO") REFERENCES "S_PILOTO"("ID_PILOTO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "S_DOCUMENTO_APLICACAO" ADD CONSTRAINT "S_DOCUMENTO_APLICACAO_ID_APLICACAO_fkey" FOREIGN KEY ("ID_APLICACAO") REFERENCES "S_APLICACAO"("ID_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "S_DOCUMENTO_APLICACAO" ADD CONSTRAINT "S_DOCUMENTO_APLICACAO_ID_TIPO_DOCUMENTO_APLICACAO_fkey" FOREIGN KEY ("ID_TIPO_DOCUMENTO_APLICACAO") REFERENCES "S_TIPO_DOCUMENTO_APLICACAO"("ID_TIPO_DOCUMENTO_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "S_DOCUMENTO_DADOS_APLICACAO" ADD CONSTRAINT "S_DOCUMENTO_DADOS_APLICACAO_ID_DOCUMENTO_APLICACAO_fkey" FOREIGN KEY ("ID_DOCUMENTO_APLICACAO") REFERENCES "S_DOCUMENTO_APLICACAO"("ID_DOCUMENTO_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "S_AREA_APLICACAO" ADD CONSTRAINT "S_AREA_APLICACAO_ID_APLICACAO_fkey" FOREIGN KEY ("ID_APLICACAO") REFERENCES "S_APLICACAO"("ID_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "S_ANALISE_APLICACAO" ADD CONSTRAINT "S_ANALISE_APLICACAO_ID_APLICACAO_fkey" FOREIGN KEY ("ID_APLICACAO") REFERENCES "S_APLICACAO"("ID_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "S_ANALISE_APLICACAO" ADD CONSTRAINT "S_ANALISE_APLICACAO_ID_TIPO_ANALISE_APLICACAO_fkey" FOREIGN KEY ("ID_TIPO_ANALISE_APLICACAO") REFERENCES "S_TIPO_ANALISE_APLICACAO"("ID_TIPO_ANALISE_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "S_ANALISE_APLICACAO" ADD CONSTRAINT "S_ANALISE_APLICACAO_ID_NOTIFICACAO_APLICACAO_fkey" FOREIGN KEY ("ID_NOTIFICACAO_APLICACAO") REFERENCES "S_NOTIFICACAO_APLICACAO"("ID_NOTIFICACAO_APLICACAO") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "S_NOTIFICACAO_APLICACAO" ADD CONSTRAINT "S_NOTIFICACAO_APLICACAO_ID_APLICACAO_fkey" FOREIGN KEY ("ID_APLICACAO") REFERENCES "S_APLICACAO"("ID_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "S_NOTIFICACAO_APLICACAO" ADD CONSTRAINT "S_NOTIFICACAO_APLICACAO_ID_FISCAL_fkey" FOREIGN KEY ("ID_FISCAL") REFERENCES "S_USUARIO"("ID_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "H_EVENTO_NOTIFICACAO" ADD CONSTRAINT "H_EVENTO_NOTIFICACAO_ID_STATUS_NOTIFICACAO_APLICACAO_fkey" FOREIGN KEY ("ID_STATUS_NOTIFICACAO_APLICACAO") REFERENCES "S_STATUS_NOTIFICACAO"("ID_STATUS_NOTIFICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "H_EVENTO_NOTIFICACAO" ADD CONSTRAINT "H_EVENTO_NOTIFICACAO_ID_NOTIFICACAO_APLICACAO_fkey" FOREIGN KEY ("ID_NOTIFICACAO_APLICACAO") REFERENCES "S_NOTIFICACAO_APLICACAO"("ID_NOTIFICACAO_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "S_AREA_PROTEGIDA" ADD CONSTRAINT "S_AREA_PROTEGIDA_ID_TIPO_AREA_PROTEGIDA_fkey" FOREIGN KEY ("ID_TIPO_AREA_PROTEGIDA") REFERENCES "S_TIPO_AREA_PROTEGIDA"("ID_TIPO_AREA_PROTEGIDA") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "S_AREA_PROTEGIDA" ADD CONSTRAINT "S_AREA_PROTEGIDA_ID_ORGANIZACAO_fkey" FOREIGN KEY ("ID_ORGANIZACAO") REFERENCES "S_ORGANIZACAO"("ID_ORGANIZACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "S_CAMINHO_APLICACAO" ADD CONSTRAINT "S_CAMINHO_APLICACAO_ID_APLICACAO_fkey" FOREIGN KEY ("ID_APLICACAO") REFERENCES "S_APLICACAO"("ID_APLICACAO") ON DELETE RESTRICT ON UPDATE CASCADE;
