-- AlterTable
ALTER TABLE "SIGA"."S_PERMISSAO" ALTER COLUMN "DH_ATUALIZACAO" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "SIGA"."S_ROLE" ALTER COLUMN "DH_ATUALIZACAO" SET DEFAULT CURRENT_TIMESTAMP;
