/*
  Warnings:

  - You are about to drop the column `ST_ORGANIZACAO_PERMISSAO` on the `S_PERMISSAO` table. All the data in the column will be lost.
  - You are about to drop the column `ST_ORGANIZACAO_ROLE` on the `S_ROLE` table. All the data in the column will be lost.
  - You are about to drop the `S_USUARIO_ORG_PERMISSAO` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `S_USUARIO_ORG_ROLE` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE "SIGA"."S_USUARIO_ORG_PERMISSAO" DROP CONSTRAINT "FK_USUARIO_ORG_PERM_ORG";

-- DropForeignKey
ALTER TABLE "SIGA"."S_USUARIO_ORG_PERMISSAO" DROP CONSTRAINT "FK_USUARIO_ORG_PERM_PERM";

-- DropForeignKey
ALTER TABLE "SIGA"."S_USUARIO_ORG_PERMISSAO" DROP CONSTRAINT "FK_USUARIO_ORG_PERM_USER";

-- DropForeignKey
ALTER TABLE "SIGA"."S_USUARIO_ORG_ROLE" DROP CONSTRAINT "FK_USUARIO_ORG_ROLE_ORG";

-- DropForeignKey
ALTER TABLE "SIGA"."S_USUARIO_ORG_ROLE" DROP CONSTRAINT "FK_USUARIO_ORG_ROLE_ROLE";

-- DropForeignKey
ALTER TABLE "SIGA"."S_USUARIO_ORG_ROLE" DROP CONSTRAINT "FK_USUARIO_ORG_ROLE_USER";

-- AlterTable
ALTER TABLE "SIGA"."S_PERMISSAO" DROP COLUMN "ST_ORGANIZACAO_PERMISSAO",
ADD COLUMN     "ID_ORGANIZACAO" INTEGER;

-- AlterTable
ALTER TABLE "SIGA"."S_ROLE" DROP COLUMN "ST_ORGANIZACAO_ROLE",
ADD COLUMN     "ID_ORGANIZACAO" INTEGER;

-- DropTable
DROP TABLE "SIGA"."S_USUARIO_ORG_PERMISSAO";

-- DropTable
DROP TABLE "SIGA"."S_USUARIO_ORG_ROLE";

-- AddForeignKey
ALTER TABLE "SIGA"."S_ROLE" ADD CONSTRAINT "S_ROLE_ID_ORGANIZACAO_fkey" FOREIGN KEY ("ID_ORGANIZACAO") REFERENCES "SIGA"."S_ORGANIZACAO"("ID_ORGANIZACAO") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SIGA"."S_PERMISSAO" ADD CONSTRAINT "S_PERMISSAO_ID_ORGANIZACAO_fkey" FOREIGN KEY ("ID_ORGANIZACAO") REFERENCES "SIGA"."S_ORGANIZACAO"("ID_ORGANIZACAO") ON DELETE SET NULL ON UPDATE CASCADE;
